_target_: src.models.instance_module.InstanceSegmentationModule
net:
  _target_: src.models.components.instance.mask2former.Mask2FormerInstance
  num_classes: 19
  backbone: facebook/mask2former-swin-small-coco-instance
  pretrained: true
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-4
  weight_decay: 0.0
  eps: 1e-8
  betas: [0.9, 0.999]
scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: true
  milestones: [44, 48]
  gamma: 0.1
compile: false
