_target_: src.models.semantic_module.SemanticSegmentationLitModule
net:
  _target_: src.models.components.semantic.unet.UNetSemantic
  num_classes: 32
  encoder_name: resnet34
  encoder_weights: imagenet
  in_channels: 3
  activation: null
  ignore_index: 255
optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 1e-3
  momentum: 0.9
  weight_decay: 1e-5
scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 20
  gamma: 0.1
compile: false
num_classes: 8
ignore_index: 255
