defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  # - lr_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: val_loss
  verbose: true
  save_last: true
  auto_insert_metric_name: false

early_stopping:
  monitor: val_loss
  patience: 30

model_summary:
  max_depth: -1
