early_stopping:
  _target_: lightning.pytorch.callbacks.EarlyStopping
  monitor: ???
  min_delta: 0.0
  patience: 15
  verbose: false
  mode: min
  strict: true
  check_finite: true
  stopping_threshold: null
  divergence_threshold: null
  check_on_train_epoch_end: null
